=== roadnarrows-robotics/rnr-sdk/netmsgs/share/netmsgs.dtd
<!--
    File: netmsgs.dtd

    $LastChangedDate$
    $Rev$

    This is RoadNarrows LLC NetMsgs DTD, which supports the definitions of
    messages intended to be packed and unpacked in architecture agnostic 
    order and sent and received across a disparate set of networked nodes.

    The NetMsgs package supports the Presentation Level of the OSI model.
    It does not include support to handle the transmission of messages across
    the network nor does it "know" how the applications interpretate the
    messages.

    Typical usage:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/DTD/netmsgs/1.0/netmsgs.dtd">
    <netmsgs>
    <meta>
    ...
    </meta>

    <field_types>
    ...
    </field_types>

    <msgdef>
    ...
    </msgdef>

    <msgdef>
    ...
    </msgdef>
    </netmsgs>

    The URI used as a system identifier with the public identifier allows
    the user agent to download the DTD and entity sets as needed.

    This version of the transitional DTD is: 1.0

    Author: Robin Knight (robin.knight@roadnarrows.com)
  
    Copyright:
    (C) 2010.  RoadNarrows LLC.
    (http://www.roadnarrows.com)
    All Rights Reserved

    EULA:
    Permission is hereby granted, without written agreement and without
    license or royalty fees, to use, copy, modify, and distribute this
    software and its documentation for any purpose, provided that
    (1) The above copyright notice and the following two paragraphs
    appear in all copies of the source code and (2) redistributions
    including binaries reproduces these notices in the supporting
    documentation.   Substantial modifications to this software may be
    copyrighted by their authors and need not follow the licensing terms
    described here, provided that the new terms are clearly indicated in
    all files where they apply  
   
    IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
    OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
    PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
    DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
    EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
    THE POSSIBILITY OF SUCH DAMAGE  
   
    THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
    FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
    "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
    PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
-->

<!-- ==================== Atribute Types =================================== -->
<!ENTITY % MsgEncoding "itv | flat">

<!ENTITY % Endian "big | little | native">

<!ENTITY % Lang "h | c | python">

<!ENTITY % Dispo "active | deprecated">

<!ENTITY % FTypeBuiltInSimple
  "u8 | s8 | char | bool | u16 | s16 | u32 | s32 | u64 | s64 | f32 | f64 |
   p32 | p64"
  >

<!ENTITY % FTypeBuiltInCompound
  "string | struct | vector"
  >

<!ENTITY % FTypeBuiltInAlias
  "byte | schar | ushort | short | uint | int | ulonglong | longlong | 
   float | double"
  >

<!ENTITY % FTypeExtended "CDATA">   <!-- really legal c/python identifier -->

<!ENTITY % FTypeBuiltIn
  "%FTypeBuiltInSimple; | %FTypeBuiltInCompound; | %FTypeBuiltInAlias;"
  >

<!ENTITY % FType "CDATA">   <!-- builtin or extended -->

<!ENTITY % Size "CDATA">    <!-- number or symbol -->


<!-- ==================== Atribute Types =================================== -->
<!ELEMENT netmsgs (meta?, field_types?, msg_types?) >
<!ATTLIST netmsgs
  encoding    (%MsgEncoding;)       "itv"
  endian      (%Endian;)            "big"
  >

<!ELEMENT meta (brief? | ns? | prologue | epilogue)* >
<!ELEMENT brief (#PCDATA) >
<!ELEMENT ns (#PCDATA) >
<!ELEMENT prologue (#PCDATA) >
<!ATTLIST prologue
  lang      (%Lang;)          #REQUIRED
  >
<!ELEMENT epilogue (#PCDATA) >
<!ATTLIST epilogue
  lang      (%Lang;)          #REQUIRED
  >

<!ELEMENT field_types (ftypedef*) >

<!ELEMENT ftypedef (fielddef*) >
<!ATTLIST ftypedef
  ftid    ID                  #REQUIRED
  ftype   %FType;             #REQUIRED
  size    %Size;              #IMPLIED
  >

<!ELEMENT msg_types (msgdef*) >

<!ELEMENT msgdef (fielddef+ | pad* | comment?)* >
<!ATTLIST msgdef
  msgid         ID            #REQUIRED
  disposition   (%Dispo;)     "active"
  >

<!ELEMENT fielddef (const? | min? | max? |  comment? | fielddef?)* >
<!ATTLIST fielddef
  fname         NMTOKEN       #REQUIRED
  ftype         %FType;       #REQUIRED
  size          %Size;        #IMPLIED
  disposition   (%Dispo;)     "active"
  >

<!ELEMENT const (#PCDATA) >
<!ELEMENT min (#PCDATA) >
<!ELEMENT max (#PCDATA) >

<!ELEMENT pad EMPTY >
<!ATTLIST pad
  count   CDATA               #IMPLIED
  >

<!ELEMENT comment (#PCDATA) >

=== roadnarrows-robotics/rnr-sdk/Hekateros/share/msgs/bsHekMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: Hekateros
 - Module:  bsHek
 - File:    bsHekMsgs.xml
 -

/*!
 \file

  $LastChangedDate: 2012-09-18 14:15:27 -0600 (Tue, 18 Sep 2012) $
  $Rev: 2286 $

  \brief BotSense client - bsProxy server Hekateros device messages.
  
  \author Robin Knight (robin.knight@roadnarrows.com)
  
 -  \copyright
 -    \h_copy 2012-2017. RoadNarrows LLC.\n
 -    http://www.roadnarrows.com\n
 -    All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      \h_botsense Server/Client Hekateros NetMsgs XML Definitions.
    </brief>
    <ns>BsHek</ns>
    <prologue lang="h">
#include "botsense/BotSense.h"
#include "Dynamixel/Dynamixel.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->
  <field_types>
    <ftypedef ftid="ServoState" ftype="struct">
      <fielddef fname="servo_id"    ftype="u8" />
      <fielddef fname="goal_speed"  ftype="s16" />
      <fielddef fname="goal_pos"    ftype="s16" />
    </ftypedef>

    <ftypedef ftid="ServoStateVec" ftype="ServoState[]" size="DYNA_ID_NUMOF" />

    <ftypedef ftid="ServoIdVec" ftype="u8[]" size="DYNA_ID_NUMOF" />

    <ftypedef ftid="ServoHealth" ftype="struct">
      <fielddef fname="servo_id"    ftype="u8" />
      <fielddef fname="alarms"      ftype="u8" />
      <fielddef fname="load"        ftype="s16" />
      <fielddef fname="volts"       ftype="u16" />
      <fielddef fname="temp"        ftype="u16" />
    </ftypedef>

    <ftypedef ftid="ServoHealthVec" ftype="ServoHealth[]"
                                    size="DYNA_ID_NUMOF" />
  </field_types>


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- Hekateros USB Serial Open Request Arguments Sub-Message -->
    <msgdef msgid="ReqOpenArgs">
      <fielddef fname="baudrate"  ftype="u32" />
    </msgdef>

    <!-- Get Version Request -->
    <msgdef msgid="ReqGetVersion" />

    <!-- Get Version Request Response) -->
    <msgdef msgid="RspGetVersion">
      <fielddef fname="version"    ftype="string" />
    </msgdef>

    <!-- Move At Speed To Request (State Response) -->
    <msgdef msgid="ReqMoveAtSpeedTo">
      <fielddef fname="move" ftype="ServoStateVec" />
    </msgdef>

    <!-- Get  At Speed To Request (State Response) -->
    <msgdef msgid="ReqGetState" />

    <!-- Freeze the Arm Request (State Response) -->
    <msgdef msgid="ReqFreeze" />

    <!-- Emergency Stop the Arm Request (State Response) -->
    <msgdef msgid="ReqEStop" />

    <!-- Calibrate Request (State Response) -->
    <msgdef msgid="ReqCalibrate" />

    <!-- State Response -->
    <msgdef msgid="RspState">
      <fielddef fname="state" ftype="ServoStateVec" />
    </msgdef>

    <!-- Get Health Request (Health Response) -->
    <msgdef msgid="ReqGetHealth">
      <fielddef fname="servo_id" ftype="ServoIdVec" />
    </msgdef>

    <!-- Get Health Response) -->
    <msgdef msgid="RspGetHealth">
      <fielddef fname="health" ftype="ServoHealthVec" />
    </msgdef>

    <!-- Clear Alarms Request (Ok Response) -->
    <msgdef msgid="ReqClearAlarms">
      <fielddef fname="servo_id" ftype="ServoIdVec" />
    </msgdef>

  </msg_types>

</netmsgs>

=== roadnarrows-robotics/rnr-sdk/botsense/bsModules/bsI2C/bsI2CMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: BotSense
 - Module:  bsI2C
 - File:    bsI2CMsgs.xml
 -

/*!
 \file

  $LastChangedDate$
  $Rev$

  \brief Client - bsProxy server raw \h_i2c bus device messages.
  
  \author Robin Knight (robin.knight@roadnarrows.com)
  
  \par Copyright:
  (C) 2010.  RoadNarrows LLC.
  (http://www.roadnarrows.com)
  \n All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      BotSense bsProxy server - client raw I2C NetMsgs XML Definition
    </brief>
    <ns>BsI2C</ns>
    <prologue lang="h">
#include "rnr/i2c-dev.h"

#include "botsense/BotSense.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
## maximum vector length
NMFVAL_LEN_MAX_VECTOR = nmBase.NMVectorMaxCount
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->
  <field_types>
  </field_types>


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- I2C Read Request -->
    <msgdef msgid="ReqRead">
      <fielddef fname="addr" ftype="u16">
      </fielddef>
      <fielddef fname="readlen" ftype="u8">
        <min>1</min>
        <max>NMFVAL_LEN_MAX_VECTOR</max>
      </fielddef>
    </msgdef>

    <!-- I2C Transaction Request -->
    <msgdef msgid="ReqTrans">
      <fielddef fname="addr" ftype="u16">
      </fielddef>
      <fielddef fname="writebuf" ftype="u8[]" />
      <fielddef fname="readlen" ftype="u8">
        <min>1</min>
        <max>NMFVAL_LEN_MAX_VECTOR</max>
      </fielddef>
    </msgdef>

    <!-- I2C Read/Transaction Response -->
    <msgdef msgid="RspRead">
      <fielddef fname="readbuf" ftype="u8[]" />
    </msgdef>

    <!-- I2C Write Request -->
    <msgdef msgid="ReqWrite">
      <fielddef fname="addr" ftype="u16">
      </fielddef>
      <fielddef fname="writebuf" ftype="u8[]" />
    </msgdef>

    <!-- I2C Write Response -->
    <msgdef msgid="RspWrite">
      <fielddef fname="byteswritten" ftype="u8" />
    </msgdef>

    <!-- I2C Scan Request -->
    <msgdef msgid="ReqScan">
    </msgdef>

    <!-- I2C Scan Response -->
    <msgdef msgid="RspScan">
      <fielddef fname="scan" ftype="u16[]" />
    </msgdef>

  </msg_types>

</netmsgs>

=== roadnarrows-robotics/rnr-sdk/Dynamixel/bsMsgs/bsDynaMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: Dynamixel
 - Module:  bsDyna
 - File:    bsDynaMsgs.xml
 -

/*!
 \file

  $LastChangedDate: 2015-01-12 10:56:06 -0700 (Mon, 12 Jan 2015) $
  $Rev: 3845 $

  \brief BotSense client - bsProxy server Dynamixel device messages.
  
  \author Robin Knight (robin.knight@roadnarrows.com)
  
  \par Copyright:
  (C) 2012-2015.  RoadNarrows LLC.
  (http://www.roadnarrows.com)
  \n All Rights Reserved
*/
-->

<!--
@EulaBegin@
 - 
 - Unless otherwise stated explicitly, all materials contained are copyrighted
 - and may not be used without RoadNarrows LLC's written consent,
 - except as provided in these terms and conditions or in the copyright
 - notice (documents and software) or other proprietary notice provided with
 - the relevant materials.
 - 
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY 
 - MEMBERS/EMPLOYEES/CONTRACTORS OF ROADNARROWS OR DISTRIBUTORS OF THIS SOFTWARE
 - BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR
 - CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS
 - DOCUMENTATION, EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN
 - ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 - 
 - THE AUTHORS AND  ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 - 
@EulaEnd@
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      \h_botsense Server/Client Dynamixel NetMsgs XML Definitions.
    </brief>
    <ns>BsDyna</ns>
    <prologue lang="h">
#include "botsense/BotSense.h"
#include "Dynamixel/Dynamixel.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->
  <field_types>
    <ftypedef ftid="WriteTuple"     ftype="struct">
      <fielddef fname="servo_id"    ftype="u8" />
      <fielddef fname="val"         ftype="u16" />
    </ftypedef>
  </field_types>


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- Dynamixel USB Serial Open Request Arguments Sub-Message -->
    <msgdef msgid="ReqOpenArgs">
      <fielddef fname="baudrate"  ftype="u32" />
    </msgdef>

    <!-- Set Baudrate Request (Ok Response) -->
    <msgdef msgid="ReqSetBaudRate">
      <fielddef fname="baudrate"  ftype="u32" />
    </msgdef>

    <!-- Read 8-btis Request -->
    <msgdef msgid="ReqRead8">
      <fielddef fname="servo_id"  ftype="u8" />
      <fielddef fname="addr"      ftype="u8" />
    </msgdef>

    <!-- Read 8-btis Response -->
    <msgdef msgid="RspRead8">
      <fielddef fname="alarms"    ftype="u8" />
      <fielddef fname="val"       ftype="u8" />
    </msgdef>

    <!-- Read 16-btis Request -->
    <msgdef msgid="ReqRead16">
      <fielddef fname="servo_id"  ftype="u8" />
      <fielddef fname="addr"      ftype="u8" />
    </msgdef>

    <!-- Read 8-btis Response -->
    <msgdef msgid="RspRead16">
      <fielddef fname="alarms"    ftype="u8" />
      <fielddef fname="val"       ftype="u16" />
    </msgdef>

    <!-- Write 8-btis Request -->
    <msgdef msgid="ReqWrite8">
      <fielddef fname="servo_id"  ftype="u8" />
      <fielddef fname="addr"      ftype="u8" />
      <fielddef fname="val"       ftype="u8" />
    </msgdef>

    <!-- Write 8-btis Response -->
    <msgdef msgid="RspWrite8">
      <fielddef fname="alarms"    ftype="u8" />
    </msgdef>

    <!-- Write 16-btis Request -->
    <msgdef msgid="ReqWrite16">
      <fielddef fname="servo_id"  ftype="u8" />
      <fielddef fname="addr"      ftype="u8" />
      <fielddef fname="val"       ftype="u16" />
    </msgdef>

    <!-- Write 16-btis Response -->
    <msgdef msgid="RspWrite16">
      <fielddef fname="alarms"    ftype="u8" />
    </msgdef>

    <!-- Sync Write Request (Ok Response) -->
    <msgdef msgid="ReqSyncWrite">
      <fielddef fname="addr"      ftype="u8" />
      <fielddef fname="data_size" ftype="u8" />
      <fielddef fname="tuples"    ftype="WriteTuple[]" size="DYNA_ID_NUMOF" />
    </msgdef>

    <!-- Ping Servo Request -->
    <msgdef msgid="ReqPing">
      <fielddef fname="servo_id"  ftype="u8" />
    </msgdef>

    <!-- Ping Servo Response -->
    <msgdef msgid="RspPing">
      <fielddef fname="pong"      ftype="bool" />
    </msgdef>

    <!-- Reset Servo Request (Ok Response) -->
    <msgdef msgid="ReqReset">
      <fielddef fname="servo_id"  ftype="u8" />
    </msgdef>

    <!-- Set Half-Duplex Control Request (Ok Response) -->
    <msgdef msgid="ReqSetHalfDuplexCtl">
      <fielddef fname="signal"  ftype="u32" />
    </msgdef>

  </msg_types>

</netmsgs>

=== roadnarrows-robotics/rnr-sdk/Kuon/sw/bsModules/bsMouseBot/bsMouseBotMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: mousebot
 - Module:  bsMouseBot
 - File:    bsMouseBotMsgs.xml
 -

/*!
 \file

  $LastChangedDate: 2012-04-25 18:46:22 -0600 (Wed, 25 Apr 2012) $
  $Rev: 1896 $

  \brief BotSense client - bsProxy server MouseBot device messages.
  
  \author Robin Knight   (robin.knight@roadnarrows.com)
  \author Rob Shiely     (rob@roadnarrows.com)
  \author Daniel Packard (daniel@roadnarrows.com)
  
 -  \copyright
 -    \h_copy 2012-2017. RoadNarrows LLC.\n
 -    http://www.roadnarrows.com\n
 -    All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      \h_botsense Server/Client MouseBot Robot NetMsgs XML Definitions.
    </brief>
    <ns>BsMouseBot</ns>
    <prologue lang="h">
#include "botsense/BotSense.h"
#include "Kuon/mousebot.h"
#include "botsense/bsMouseBot.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
from bsMouseBotCore import MOUSEBOT_USS_NUMOF, MOUSEBOT_IR_NUMOF, MOUSEBOT_USS_ECHO_MAX_MAX
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->





  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- Client Lifeline -->
    <msgdef msgid="ReqAlive">
    </msgdef>

    <!-- Set tty Address Request -->
    <msgdef msgid="ReqOpenParams">
      <fielddef fname="server"        ftype="bool" />
      <fielddef fname="FrontAddr"     ftype="string" />
      <fielddef fname="RearAddr"      ftype="string" />
    </msgdef>

    <!-- Set Motor Speeds Request -->
    <msgdef msgid="ReqSetMotorSpeeds">
      <fielddef fname="speedleft"     ftype="s16" />
      <fielddef fname="speedright"    ftype="s16" />
    </msgdef>

    <!-- Alter Slew Rate Request -->
    <msgdef msgid="ReqAlterSlew">
      <fielddef fname="slewFL"        ftype="u16"/>
      <fielddef fname="slewFR"        ftype="u16"/>
      <fielddef fname="slewRL"        ftype="u16"/>
      <fielddef fname="slewRR"        ftype="u16"/>
    </msgdef>

    <!-- Alter Brake Rate Request -->
    <msgdef msgid="ReqAlterBrake">
      <fielddef fname="brakeFL"        ftype="u16"/>
      <fielddef fname="brakeFR"        ftype="u16"/>
      <fielddef fname="brakeRL"        ftype="u16"/>
      <fielddef fname="brakeRR"        ftype="u16"/>
    </msgdef>

    <!-- Stop the Robot -->
    <msgdef msgid="ReqStop">
    </msgdef>

  </msg_types>

</netmsgs>
