=== roadnarrows-robotics/rnr-sdk/netmsgs/share/netmsgs.dtd
<!--
    File: netmsgs.dtd

    $LastChangedDate$
    $Rev$

    This is RoadNarrows LLC NetMsgs DTD, which supports the definitions of
    messages intended to be packed and unpacked in architecture agnostic 
    order and sent and received across a disparate set of networked nodes.

    The NetMsgs package supports the Presentation Level of the OSI model.
    It does not include support to handle the transmission of messages across
    the network nor does it "know" how the applications interpretate the
    messages.

    Typical usage:

    <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/DTD/netmsgs/1.0/netmsgs.dtd">
    <netmsgs>
    <meta>
    ...
    </meta>

    <field_types>
    ...
    </field_types>

    <msgdef>
    ...
    </msgdef>

    <msgdef>
    ...
    </msgdef>
    </netmsgs>

    The URI used as a system identifier with the public identifier allows
    the user agent to download the DTD and entity sets as needed.

    This version of the transitional DTD is: 1.0

    Author: Robin Knight (robin.knight@roadnarrows.com)
  
    Copyright:
    (C) 2010.  RoadNarrows LLC.
    (http://www.roadnarrows.com)
    All Rights Reserved

    EULA:
    Permission is hereby granted, without written agreement and without
    license or royalty fees, to use, copy, modify, and distribute this
    software and its documentation for any purpose, provided that
    (1) The above copyright notice and the following two paragraphs
    appear in all copies of the source code and (2) redistributions
    including binaries reproduces these notices in the supporting
    documentation.   Substantial modifications to this software may be
    copyrighted by their authors and need not follow the licensing terms
    described here, provided that the new terms are clearly indicated in
    all files where they apply  
   
    IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
    OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
    PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
    DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
    EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
    THE POSSIBILITY OF SUCH DAMAGE  
   
    THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
    INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
    FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
    "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
    PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
-->

<!-- ==================== Atribute Types =================================== -->
<!ENTITY % MsgEncoding "itv | flat">

<!ENTITY % Endian "big | little | native">

<!ENTITY % Lang "h | c | python">

<!ENTITY % Dispo "active | deprecated">

<!ENTITY % FTypeBuiltInSimple
  "u8 | s8 | char | bool | u16 | s16 | u32 | s32 | u64 | s64 | f32 | f64 |
   p32 | p64"
  >

<!ENTITY % FTypeBuiltInCompound
  "string | struct | vector"
  >

<!ENTITY % FTypeBuiltInAlias
  "byte | schar | ushort | short | uint | int | ulonglong | longlong | 
   float | double"
  >

<!ENTITY % FTypeExtended "CDATA">   <!-- really legal c/python identifier -->

<!ENTITY % FTypeBuiltIn
  "%FTypeBuiltInSimple; | %FTypeBuiltInCompound; | %FTypeBuiltInAlias;"
  >

<!ENTITY % FType "CDATA">   <!-- builtin or extended -->

<!ENTITY % Size "CDATA">    <!-- number or symbol -->


<!-- ==================== Atribute Types =================================== -->
<!ELEMENT netmsgs (meta?, field_types?, msg_types?) >
<!ATTLIST netmsgs
  encoding    (%MsgEncoding;)       "itv"
  endian      (%Endian;)            "big"
  >

<!ELEMENT meta (brief? | ns? | prologue | epilogue)* >
<!ELEMENT brief (#PCDATA) >
<!ELEMENT ns (#PCDATA) >
<!ELEMENT prologue (#PCDATA) >
<!ATTLIST prologue
  lang      (%Lang;)          #REQUIRED
  >
<!ELEMENT epilogue (#PCDATA) >
<!ATTLIST epilogue
  lang      (%Lang;)          #REQUIRED
  >

<!ELEMENT field_types (ftypedef*) >

<!ELEMENT ftypedef (fielddef*) >
<!ATTLIST ftypedef
  ftid    ID                  #REQUIRED
  ftype   %FType;             #REQUIRED
  size    %Size;              #IMPLIED
  >

<!ELEMENT msg_types (msgdef*) >

<!ELEMENT msgdef (fielddef+ | pad* | comment?)* >
<!ATTLIST msgdef
  msgid         ID            #REQUIRED
  disposition   (%Dispo;)     "active"
  >

<!ELEMENT fielddef (const? | min? | max? |  comment? | fielddef?)* >
<!ATTLIST fielddef
  fname         NMTOKEN       #REQUIRED
  ftype         %FType;       #REQUIRED
  size          %Size;        #IMPLIED
  disposition   (%Dispo;)     "active"
  >

<!ELEMENT const (#PCDATA) >
<!ELEMENT min (#PCDATA) >
<!ELEMENT max (#PCDATA) >

<!ELEMENT pad EMPTY >
<!ATTLIST pad
  count   CDATA               #IMPLIED
  >

<!ELEMENT comment (#PCDATA) >

=== roadnarrows-robotics/rnr-sdk/netmsgs/examples/AstroMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package:   netmsgs
 -
 - Program:   nmExample
 -
 - File: AstroMsg.xml
 -

/*!
 \file

  $LastChangedDate$
  $Rev$

  \brief Example RoadNarrows NetMsgs XML definitions.
  
  \author Robin Knight (robin.knight@roadnarrows.com)
  
  \par Copyright:
  (C) 2010.  RoadNarrows LLC.
  (http://www.roadnarrows.com)
  \n All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">
  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>Example ITV XML Definitions</brief>
    <ns>Astro</ns>
    <prologue lang="h">
#include "nmExample.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
## Minimum star temperature
STAR_TEMP_K_MIN = 1000

## Maximum star temperature
STAR_TEMP_K_MAX = 50000

#
# Star constellation designations are greek leters from brightest to dimmest
#

## 1st star
ALPHA   =   0     

## 2nd star
BETA    =   1     

## 3rd star
GAMMA   =   2     

## 4th star
DELTA   =   3     

## 5th star
EPSILON =   4     

## 6th star
ZETA    =   5     

## 7th star
ETA     =   6     

## 8th star
THETA   =   7     

## 9th star
IOTA    =   8     

## 10th star
KAPPA   =   9     

## 11th star
LAMBDA  =  10     

## 12th star
MU      =  11     

## 13th star
NU      =  12     

## 14th star
XI      =  13     

## 15th star
OMICRON =  14     

## 16th star
PI      =  15     
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->

  <field_types>
    <ftypedef ftid="SpectralClass" ftype="char" />

    <ftypedef ftid="SpectralColor" ftype='string' size="16" />

    <ftypedef ftid="TempK" ftype="u32" />

    <ftypedef ftid="Star" ftype="struct">
      <fielddef fname="Name" ftype="string" size="32" />
      <fielddef fname="Type" ftype="SpectralClass" />
      <fielddef fname="Color" ftype="SpectralColor" />
      <fielddef fname="TempK" ftype="TempK">
        <min>STAR_TEMP_K_MIN</min>
        <max>STAR_TEMP_K_MAX</max>
      </fielddef>
      <fielddef fname="MassSun" ftype="f32">
        <min>0.1</min>
        <max>100.0</max>
      </fielddef>
    </ftypedef>

    <ftypedef ftid="Sun" ftype="Star" />

    <ftypedef ftid="StarGroup" ftype="Star[]" size="16" />

    <ftypedef ftid="Constellation" ftype="struct">
      <fielddef fname="Name" ftype="string" size="32" />
      <fielddef fname="OldName" ftype="string" disposition="deprecated" />
      <fielddef fname="Designation" ftype="u8[]" size="16">
        <min>ALPHA</min>
        <max>PI</max>
      </fielddef>
      <fielddef fname="Star" ftype="StarGroup" />
    </ftypedef>
  </field_types>


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->

  <msg_types>
    <!-- Ok Response -->
    <msgdef msgid="RspOk">
    </msgdef>

    <!-- Error Response -->
    <msgdef msgid="RspErr">
      <fielddef fname="ECode" ftype="u8" />
      <fielddef fname="EMsg" ftype="string">
      </fielddef>
    </msgdef>

    <!-- Zodiac Constellatio Family Command -->
    <msgdef msgid="CmdZodiac">
      <fielddef fname="Family" ftype="string" size="32" >
        <const>"Zodiac"</const></fielddef>
      <fielddef fname="Constellation" ftype="Constellation" />
    </msgdef>
  
    <!-- Ursa Major Constellatio Family Command -->
    <msgdef msgid="CmdUrsa">
      <fielddef fname="Family" ftype="string" size="32">
        <const>"Ursa Major"</const>
      </fielddef>
      <fielddef fname="Constellation" ftype="Constellation" />
    </msgdef>
  
    <!-- Music of the Spheres Command -->
    <msgdef msgid="CmdMusicOfTheSpheres" disposition="deprecated">
      <fielddef fname="geometry" ftype="u32" />
      <fielddef fname="cosmology" ftype="u32" />
      <fielddef fname="astrology" ftype="u32" />
      <fielddef fname="harmonics" ftype="u32" />
      <fielddef fname="music" ftype="u32" />
    </msgdef>
  
    <!-- Fractal -->
    <msgdef msgid="Fractal">
      <fielddef fname="Self" ftype="struct">
        <fielddef fname="Point" ftype="s32[]" size="4" />
        <fielddef fname="Self" ftype="struct">
          <fielddef fname="Point" ftype="s32[]" size="4" />
          <fielddef fname="Self" ftype="struct">
            <fielddef fname="Point" ftype="s32[]" size="4" />
          </fielddef>
        </fielddef>
      </fielddef>
      <fielddef fname="Constellation" ftype="Constellation" />
    </msgdef>
  
    <!-- Test Signal -->
    <msgdef msgid="TstSignal">
    </msgdef>
  
    <!-- Test the Universe Command -->
    <msgdef msgid="CmdUniverse">
      <pad />
      <fielddef fname="Truth" ftype="bool" />
      <fielddef fname="Aura" ftype="char" />
      <fielddef fname="Gluon" ftype="u8" />
      <fielddef fname="Electron" ftype="s8" />
      <pad count="3" />
      <fielddef fname="Planet" ftype="u16" />
      <fielddef fname="StellarObj" ftype="s16" />
      <fielddef fname="StarSystem" ftype="u32" />
      <fielddef fname="Galaxy" ftype="s32">
        <min>-99</min>
        <max>9909</max>
       </fielddef>
      <fielddef fname="GalaxyGroup" ftype="u64" />
      <fielddef fname="Filament" ftype="s64" />
      <fielddef fname="Ether" ftype="u32" disposition="deprecated" />
      <fielddef fname="VisUnivLY" ftype="f32" />
      <fielddef fname="FullUnivLY" ftype="f64" />
      <fielddef fname="HiddenDim" ftype="p32" />
      <fielddef fname="ParallelUniv" ftype="p64" />
      <fielddef fname="TheUnamed" ftype="string" size="42" />
      <fielddef fname="Math" ftype="struct">
        <fielddef fname="One" ftype="u16" />
        <fielddef fname="Two" ftype="u32" />
        <fielddef fname="DotDotDot" ftype="u64" />
      </fielddef>
      <fielddef fname="Physics" ftype="uint[]" size="53" />
      <fielddef fname="StarType" ftype="SpectralClass" />
      <fielddef fname="StarInfo" ftype="Star" />
    </msgdef>
  </msg_types>
</netmsgs>

=== roadnarrows-robotics/rnr-sdk/Kuon/sw/bsModules/bsKuon/bsKuonMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: kuon
 - Module:  bsKuon
 - File:    bsKuonMsgs.xml
 -

/*!
 \file

  $LastChangedDate$
  $Rev$

  \brief BotSense client - bsProxy server Kuon device messages.
  
  \author Robin Knight   (robin.knight@roadnarrows.com)
  \author Rob Shiely     (rob@roadnarrows.com)
  \author Daniel Packard (daniel@roadnarrows.com)
  
  \par Copyright:
  (C) 2010.  RoadNarrows LLC.
  (http://www.roadnarrows.com)
  \n All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      \h_botsense Server/Client Kuon Robot NetMsgs XML Definitions.
    </brief>
    <ns>BsKuon</ns>
    <prologue lang="h">
#include "botsense/BotSense.h"
#include "Kuon/kuon.h"
#include "botsense/bsKuon.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
from bsKuonCore import KUON_USS_NUMOF, KUON_IR_NUMOF, KUON_USS_ECHO_MAX_MAX
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- Set tty Address Request -->
    <msgdef msgid="ReqOpenParams">
      <fielddef fname="server"        ftype="u8" />
      <fielddef fname="FrontAddr"     ftype="string" />
      <fielddef fname="RearAddr"      ftype="string" />
    </msgdef>

    <!-- Client Lifeline -->
    <msgdef msgid="ReqAlive">
    </msgdef>

    <!-- Set Motor Speeds Request -->
    <msgdef msgid="ReqSetMotorSpeeds">
      <fielddef fname="speedleft"     ftype="s16" />
      <fielddef fname="speedright"    ftype="s16" />
    </msgdef>

    <!-- Alter Slew Rate Request -->
    <msgdef msgid="ReqAlterSlew">
      <fielddef fname="slewFL"        ftype="u16"/>
      <fielddef fname="slewFR"        ftype="u16"/>
      <fielddef fname="slewRL"        ftype="u16"/>
      <fielddef fname="slewRR"        ftype="u16"/>
    </msgdef>

    <!-- Alter Brake Rate Request -->
    <msgdef msgid="ReqAlterBrake">
      <fielddef fname="brakeFL"        ftype="u16"/>
      <fielddef fname="brakeFR"        ftype="u16"/>
      <fielddef fname="brakeRL"        ftype="u16"/>
      <fielddef fname="brakeRR"        ftype="u16"/>
    </msgdef>

    <!-- Stop the Robot -->
    <msgdef msgid="ReqStop">
    </msgdef>

    <!-- Zero Out IMU Gyroscope Accumulators Request -->
    <msgdef msgid="ReqZeroOutImuGyros" />

    <!-- Read IMU Processed Data Request -->
    <msgdef msgid="ReqReadImu" />

    <!-- Read IMU Processed Data Response -->
    <msgdef msgid="RspReadImu">
      <fielddef fname="ax"        ftype="f32"/>
      <fielddef fname="ay"        ftype="f32"/>
      <fielddef fname="az"        ftype="f32"/>
      <fielddef fname="gx"        ftype="f32"/>
      <fielddef fname="gy"        ftype="f32"/>
      <fielddef fname="gz"        ftype="f32"/>
      <fielddef fname="temp"      ftype="f32"/>
    </msgdef>

    <!-- Read IMU Decoupled Angles Request -->
    <msgdef msgid="ReqReadImuDecoupAngles" />

    <!-- Read IMU Decoupled Angles Response -->
    <msgdef msgid="RspReadImuDecoupAngles">
      <fielddef fname="heading"   ftype="f32"/>
      <fielddef fname="pitch"     ftype="f32"/>
      <fielddef fname="roll"      ftype="f32"/>
    </msgdef>

  </msg_types>

</netmsgs>

=== roadnarrows-robotics/rnr-sdk/botsense/bsModules/bsSerial/bsSerialMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: BotSense
 - Module:  bsSerial
 - File:    bsSerialMsgs.xml
 -

/*!
 \file

  $LastChangedDate: 2010-09-13 10:25:05 -0600 (Mon, 13 Sep 2010) $
  $Rev: 581 $

  \brief Client - bsProxy server raw RS-232 serial messages.
  
  \author Robin Knight (robin.knight@roadnarrows.com)
  
 -  \copyright
 -    \h_copy 2010-2017. RoadNarrows LLC.\n
 -    http://www.roadnarrows.com\n
 -    All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      BotSense bsProxy server - client raw serial NetMsgs XML Definition
    </brief>
    <ns>BsSerial</ns>
    <prologue lang="h">
      #include "botsense/BotSense.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python">
## maximum vector length
NMFVAL_LEN_MAX_VECTOR = nmBase.NMVectorMaxCount
    </prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->
  <field_types>
  </field_types>


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- Serial Open Request Arguments Sub-Message -->
    <msgdef msgid="ReqOpenArgs">
      <fielddef fname="baudrate"  ftype="u32" />
      <fielddef fname="bytesize"  ftype="u8" />
      <fielddef fname="parity"    ftype="char" />
      <fielddef fname="stopbits"  ftype="u8" />
      <fielddef fname="rtscts"    ftype="bool" />
      <fielddef fname="xonxoff"   ftype="bool" />
    </msgdef>

      <!-- Serial Read Request -->
    <msgdef msgid="ReqRead">
      <fielddef fname="readlen" ftype="u8">
        <min>1</min>
        <max>NMFVAL_LEN_MAX_VECTOR</max>
      </fielddef>
    </msgdef>

    <!-- Serial Transaction Request -->
    <msgdef msgid="ReqTrans">
      <fielddef fname="writebuf" ftype="u8[]" />
      <fielddef fname="readlen" ftype="u8">
        <min>1</min>
        <max>NMFVAL_LEN_MAX_VECTOR</max>
      </fielddef>
    </msgdef>

    <!-- Serial Read/Transaction Response -->
    <msgdef msgid="RspRead">
      <fielddef fname="readbuf" ftype="u8[]" />
    </msgdef>

    <!-- Serial Write Request -->
    <msgdef msgid="ReqWrite">
      <fielddef fname="writebuf" ftype="u8[]" />
    </msgdef>

    <!-- Serial Write Response -->
    <msgdef msgid="RspWrite">
      <fielddef fname="byteswritten" ftype="u8" />
    </msgdef>

  </msg_types>

</netmsgs>

=== roadnarrows-robotics/rnr-sdk/botsense/bsModules/bsNull/bsNullMsgs.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE netmsgs PUBLIC "-//www.roadnarrows.com//DTD NETMSGS 1.0//EN"
          "http://www.roadnarrows.com/xml/netmsgs/1.0/netmsgs.dtd">

<!--
 - Package: BotSense
 - Module:  bsNull
 - File:    bsNullMsgs.xml
 -

/*!
 \file

  $LastChangedDate$
  $Rev$

  \brief Client - bsProxy server /dev/null device messages.
  
  \author Robin Knight (robin.knight@roadnarrows.com)
  
  \par Copyright:
  (C) 2010.  RoadNarrows LLC.
  (http://www.roadnarrows.com)
  \n All Rights Reserved
*/

 - Permission is hereby granted, without written agreement and without
 - license or royalty fees, to use, copy, modify, and distribute this
 - software and its documentation for any purpose, provided that
 - (1) The above copyright notice and the following two paragraphs
 - appear in all copies of the source code and (2) redistributions
 - including binaries reproduces these notices in the supporting
 - documentation.   Substantial modifications to this software may be
 - copyrighted by their authors and need not follow the licensing terms
 - described here, provided that the new terms are clearly indicated in
 - all files where they apply.
 -
 - IN NO EVENT SHALL THE AUTHOR, ROADNARROWS LLC, OR ANY MEMBERS/EMPLOYEES
 - OF ROADNARROW LLC OR DISTRIBUTORS OF THIS SOFTWARE BE LIABLE TO ANY
 - PARTY FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
 - DAMAGES ARISING OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION,
 - EVEN IF THE AUTHORS OR ANY OF THE ABOVE PARTIES HAVE BEEN ADVISED OF
 - THE POSSIBILITY OF SUCH DAMAGE.
 -
 - THE AUTHOR AND ROADNARROWS LLC SPECIFICALLY DISCLAIM ANY WARRANTIES,
 - INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 - FITNESS FOR A PARTICULAR PURPOSE. THE SOFTWARE PROVIDED HEREUNDER IS ON AN
 - "AS IS" BASIS, AND THE AUTHORS AND DISTRIBUTORS HAVE NO OBLIGATION TO
 - PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 -
-->

<netmsgs encoding="itv" endian="big">

  <!-- ........................................................................
    - Meta Data to Tweak Source Generation
    ....................................................................... -->
  <meta>
    <brief>
      BotSense bsProxy server - client /dev/null NetMsgs XML Definition
    </brief>
    <ns>BsNull</ns>
    <prologue lang="h">
#include "botsense/BotSense.h"
    </prologue>
    <epilogue lang="h"></epilogue>
    <prologue lang="c"></prologue>
    <epilogue lang="c"></epilogue>
    <prologue lang="python"></prologue>
    <epilogue lang="python"></epilogue>
  </meta>

  <!-- ........................................................................
    - Extended Field Types (Optional)
    ....................................................................... -->
  <field_types>
  </field_types>


  <!-- ........................................................................
    - Message Definitions
    ....................................................................... -->
  <msg_types>

    <!-- Null Write Request -->
    <msgdef msgid="ReqWrite">
      <fielddef fname="writebuf" ftype="u8[]" />
    </msgdef>

    <!-- Null Write Response -->
    <msgdef msgid="RspWrite">
      <fielddef fname="byteswritten" ftype="u8" />
    </msgdef>

  </msg_types>

</netmsgs>
